# lib/config.sh — Language detection, i18n, config loading
# Sourced by harn.sh — do not execute directly

# ── Config loading ──────────────────────────────────────────────────────────────

# Detect language: env HARN_LANG → config LANG_OVERRIDE → $LANG/$LC_ALL → en
_detect_lang() {
  # 1. Explicit env var
  if [[ -n "${HARN_LANG:-}" ]]; then
    HARN_LANG="${HARN_LANG}"
    return
  fi
  # 2. Config file override (read directly — load_config may not have run yet)
  if [[ -f "$CONFIG_FILE" ]]; then
    local cfg_lang
    cfg_lang=$(grep -E '^LANG_OVERRIDE=' "$CONFIG_FILE" 2>/dev/null | head -1 | cut -d= -f2- | tr -d '"' || true)
    if [[ -n "$cfg_lang" ]]; then
      HARN_LANG="$cfg_lang"
      return
    fi
  fi
  # 3. System locale
  local sys_locale="${LANG:-${LC_ALL:-}}"
  if [[ "$sys_locale" == ko* ]]; then
    HARN_LANG="ko"
    return
  fi
  # 4. Default
  HARN_LANG="en"
}

# Set UI string variables based on HARN_LANG
_i18n_load() {
  if [[ "$HARN_LANG" == "ko" ]]; then
    I18N_LANG_NAME="한국어"
    I18N_INIT_LANG_PROMPT="사용 언어"
    I18N_INIT_BACKLOG_PROMPT="백로그 파일 경로 (프로젝트 루트 기준)"
    I18N_INIT_BACKLOG_DEFAULT="sprint-backlog.md"
    I18N_INIT_MAX_QA_PROMPT="최대 QA 재시도 횟수"
    I18N_INIT_GIT_PROMPT="Git 통합 활성화"
    I18N_INIT_SAVED="설정이 저장됐어요"
    I18N_DOCTOR_TITLE="harn 환경 진단"
    I18N_DOCTOR_OK="정상"
    I18N_DOCTOR_WARN="경고"
    I18N_DOCTOR_FAIL="실패"
    I18N_CONFIG_SET_DONE="설정 저장됨"
    I18N_CONFIG_SET_USAGE="사용법: harn config set <key> <value>"
    I18N_LANG_SELECT="사용할 언어를 선택하세요"
    # usage()
    I18N_USAGE_TITLE="사용법"
    I18N_USAGE_CMD="harn <명령어>"
    I18N_USAGE_SETUP="설정"
    I18N_USAGE_BACKLOG="백로그"
    I18N_USAGE_RUN="실행"
    I18N_USAGE_STEPS="단계별 실행"
    I18N_USAGE_MONITOR="모니터링"
    I18N_USAGE_INIT="초기 설정 (첫 실행 또는 재설정)"
    I18N_USAGE_CONFIG="현재 설정 보기"
    I18N_USAGE_CONFIG_SET="특정 설정 변경"
    I18N_USAGE_CONFIG_REGEN="HINT_* 값으로 커스텀 프롬프트 재생성"
    I18N_USAGE_BACKLOG_CMD="백로그 항목 목록"
    I18N_USAGE_ADD="새 백로그 항목 추가 (AI 보조)"
    I18N_USAGE_DISCOVER="코드베이스 분석 후 작업 발굴"
    I18N_USAGE_START="항목 선택 후 전체 루프 실행"
    I18N_USAGE_AUTO="자동 감지: 재개 / 시작 / 발굴"
    I18N_USAGE_ALL="대기 중인 항목 전부 순차 실행 (마지막에 회고)"
    I18N_USAGE_PLAN="플래너 재실행"
    I18N_USAGE_CONTRACT="스코프 협상"
    I18N_USAGE_IMPLEMENT="제너레이터 실행"
    I18N_USAGE_EVALUATE="이밸류에이터 실행"
    I18N_USAGE_NEXT="다음 스프린트로 이동"
    I18N_USAGE_STATUS="현재 실행 상태"
    I18N_USAGE_TAIL="실시간 로그 출력"
    I18N_USAGE_RUNS="전체 실행 목록"
    I18N_USAGE_RESUME="이전 실행 재개"
    I18N_USAGE_STOP="루프 중단"
    I18N_USAGE_TIP="루프 실행 중에도 단계 사이에 추가 지시사항을 넣을 수 있어요."
    I18N_USAGE_SMART="스마트"
    I18N_USAGE_DO="자연어 명령 (AI가 적절한 작업으로 라우팅)"
    I18N_USAGE_TEAM="tmux로 병렬 에이전트 실행 (N = 에이전트 수)"
    I18N_WELCOME_TIPS="시작하기"
    I18N_WELCOME_DOCTOR="환경 진단"
    # doctor
    I18N_DOCTOR_VERSION="버전"
    I18N_DOCTOR_BACKENDS="AI 백엔드"
    I18N_DOCTOR_NOT_FOUND="설치되지 않음"
    I18N_DOCTOR_INSTALL="설치"
    I18N_DOCTOR_ACTIVE_BACKEND="활성 백엔드"
    I18N_DOCTOR_NO_BACKEND="AI 백엔드 없음 — harn init 실행 필요"
    I18N_DOCTOR_GIT_SECTION="Git"
    I18N_DOCTOR_GH_AUTH_WARN="인증 안 됨 — gh auth login 실행 필요"
    I18N_DOCTOR_GH_NOT_FOUND="설치되지 않음"
    I18N_DOCTOR_PROJECT_REPO="프로젝트 저장소"
    I18N_DOCTOR_CONFIG_SECTION="harn 설정"
    I18N_DOCTOR_CONFIG_FOUND="설정 파일 있음"
    I18N_DOCTOR_CONFIG_NOT_FOUND="설정 안 됨 (harn init 실행 필요)"
    I18N_DOCTOR_GIT_INTEGRATION="Git 통합"
    I18N_DOCTOR_SPRINT_COUNT="스프린트 수"
    I18N_DOCTOR_AI_BACKEND="AI 백엔드"
    I18N_DOCTOR_CUSTOM_PROMPTS="커스텀 프롬프트"
    I18N_DOCTOR_MODELS="모델"
    I18N_DOCTOR_ACTIVE_RUN="현재 실행"
    I18N_DOCTOR_SPRINT="스프린트"
    I18N_DOCTOR_NO_RUN="현재 실행 없음"
    I18N_DOCTOR_DEPS="기타 의존성"
    I18N_DOCTOR_OPTIONAL="선택사항"
    I18N_DOCTOR_ALL_OK="모든 핵심 검사 통과."
    I18N_DOCTOR_FAIL_MSG="하나 이상의 핵심 검사 실패. harn init 실행 필요"
    # no-config warning
    I18N_NO_CONFIG_WARN=".harn_config 파일이 없습니다."
    I18N_NO_CONFIG_SETUP="초기 설정을 시작합니다..."
    # cmd_init
    I18N_INIT_TITLE="harn 초기 설정"
    I18N_INIT_OVERWRITE="설정 파일이 이미 있습니다. 덮어쓸까요? [y/N]: "
    I18N_INIT_CANCELLED="초기화 취소됨"
    I18N_INIT_AI_MODELS="AI 모델 설정"
    I18N_INIT_AI_MODELS_HINT="↑↓ 방향키로 이동, Enter로 선택, Ctrl+Q로 취소"
    I18N_INIT_SPRINT_STRUCTURE="스프린트 구조"
    I18N_INIT_SPRINT_COUNT_PROMPT="스프린트 수 [2]: "
    I18N_INIT_SPRINT_ROLES_HINT="각 스프린트의 목표/역할을 입력하세요 (Enter = 기본값 사용)"
    I18N_INIT_SPRINT_ROLE_PROMPT="스프린트 %s 역할: "
    I18N_INIT_SPRINT_INVALID="잘못된 스프린트 수 '%s' — 기본값 2로 설정"
    I18N_INIT_GIT_SECTION="Git 통합"
    I18N_INIT_GIT_ENABLE_PROMPT="Git 통합을 활성화할까요? [y/N]: "
    I18N_INIT_GIT_GUIDE_TITLE="Git 커밋 가이드라인"
    I18N_INIT_GIT_GUIDE_HINT="커밋 컨벤션 등을 입력하세요.\n  에이전트 프롬프트에 반영됩니다. (Enter = 건너뜀)"
    I18N_INIT_HINTS_TITLE="에이전트별 특별 지시사항"
    I18N_INIT_HINTS_HINT="프로젝트 아키텍처, 기술 스택, 코딩 컨벤션 등을 입력하세요.\n  AI CLI가 기본 프롬프트에 자연스럽게 통합합니다. (Enter = 건너뜀)"
    I18N_INIT_HINT_PLANNER="Planner   — 스펙/스프린트 계획 지시사항: "
    I18N_INIT_HINT_GENERATOR="Generator — 구현 지시사항: "
    I18N_INIT_HINT_EVALUATOR="Evaluator — QA/평가 지시사항: "
    I18N_INIT_CONFIG_SAVED="설정 파일 생성됨"
    I18N_INIT_GEN_PROMPTS="AI CLI로 커스텀 프롬프트 생성 중"
    I18N_INIT_COMPLETE="초기화 완료!"
    I18N_INIT_HINT_BACKLOG="  harn backlog  — 백로그 항목 보기"
    I18N_INIT_HINT_START="  harn start    — 루프 시작"
    # AI CLI check / backend selection
    I18N_NO_AI_CLI="AI CLI를 찾을 수 없어요."
    I18N_NO_AI_CLI_HINT="harn은 GitHub Copilot CLI, Claude CLI, OpenAI Codex CLI, 또는 Gemini CLI가 필요합니다."
    I18N_AI_BACKEND_TITLE="기본 AI 백엔드"
    I18N_AI_USING_COPILOT="${G}✓${N} ${W}copilot${N} 사용 (GitHub Copilot CLI 감지됨)"
    I18N_AI_USING_CLAUDE="${G}✓${N} ${W}claude${N} 사용 (Anthropic Claude CLI 감지됨)"
    I18N_AI_USING_CODEX="${G}✓${N} ${W}codex${N} 사용 (OpenAI Codex CLI 감지됨)"
    I18N_AI_USING_GEMINI="${G}✓${N} ${W}gemini${N} 사용 (Google Gemini CLI 감지됨)"
    # cmd_backlog
    I18N_BACKLOG_TITLE="대기 중인 백로그 항목:"
    I18N_BACKLOG_EMPTY="(없음 — 모두 완료!)"
    I18N_BACKLOG_RUN="실행: ${W}harn start${N} — 항목을 선택해 전체 루프를 시작하세요"
    # cmd_start
    I18N_START_SELECT_ITEM="백로그 항목 선택"
    I18N_START_NO_PENDING="대기 중인 항목이 없습니다. 먼저 항목을 추가하세요."
    I18N_START_DISCOVER_HINT="항목 발굴: harn discover"
    I18N_START_ENTER_NUM="번호를 입력하세요 (1–%s): "
    I18N_START_SPRINT_COUNT_PROMPT="스프린트 수 [1]: "
    I18N_START_SPRINT_COUNT_INVALID="잘못된 스프린트 수 — 1로 설정"
    I18N_START_SELECTED="선택됨:"
    I18N_START_INVALID="잘못된 입력:"
    I18N_START_RUN_CREATED="실행 생성됨:"
    I18N_START_VIEW_LOG="실시간 로그 보기: ${W}harn tail${N}  →"
    I18N_START_PLAN_FAILED="플래닝 단계에서 실패했습니다. 로그를 확인하고 재시도하세요:"
    I18N_START_AUTO_LOOP="자동 실행 시작"
    I18N_START_LOOP_DETAIL="초기화 완료. 스프린트 루프를 자동으로 실행합니다 (contract → implement → evaluate → next, 최대 %s 스프린트)."
    I18N_START_LOOP_INTERRUPTED="스프린트 루프가 중단됐습니다. 실패 지점을 확인하고 재개하세요: 'harn resume %s'"
    I18N_START_COMPLETE="harn start 전체 자동 실행 완료"
    I18N_START_MAX_SPRINT="최대 스프린트 수(%s)에 도달했습니다. 계속하려면 'harn start'를 실행하세요."
    # cmd_plan
    I18N_PLAN_STEP="플래닝 단계"
    I18N_PLAN_TEXT_NOT_FOUND="plan.text를 찾을 수 없음 — 슬러그/프롬프트를 플랜 텍스트로 사용"
    I18N_PLAN_MARKERS_NOT_FOUND="섹션 마커를 찾을 수 없음 — 전체 출력을 spec.md로 저장"
    I18N_PLAN_ITEM_IN_PROGRESS="백로그: ${W}%s${N} → 진행 중"
    I18N_PLAN_LINE_UPDATED="백로그 플랜 라인 업데이트됨:"
    I18N_PLAN_LINE_FAILED="백로그 플랜 업데이트 실패: 슬러그를 찾을 수 없음"
    I18N_PLAN_LINE_UNCHANGED="백로그 플랜 라인 변경 없음 (이미 최신)"
    I18N_PLAN_LINE_EXCEPTION="백로그 플랜 업데이트 중 오류 발생"
    I18N_PLAN_COMPLETE="플래닝 완료"
    # cmd_contract
    I18N_CONTRACT_EXISTS="스코프가 이미 존재합니다. 재생성하려면 삭제하세요:"
    I18N_CONTRACT_STEP="스프린트 %s — 스코프 협상"
    I18N_CONTRACT_REVIEWING="이밸류에이터가 스코프 검토 중..."
    I18N_CONTRACT_APPROVED="스프린트 %s 스코프 승인됨"
    I18N_CONTRACT_NEEDS_REVISION="스코프 수정 필요 — 수정 중..."
    I18N_CONTRACT_REVISED="스프린트 %s 스코프 수정 완료"
    I18N_CONTRACT_NEXT="다음 단계: harn implement"
    # cmd_implement
    I18N_IMPL_NO_SCOPE="스프린트 %s의 스코프가 없습니다. 실행: harn contract"
    I18N_IMPL_STEP="스프린트 %s — 개발 (반복 %s)"
    I18N_IMPL_COMPLETE="스프린트 %s 구현 완료 (반복 %s)"
    I18N_IMPL_NEXT="다음 단계: harn evaluate"
    # cmd_evaluate
    I18N_EVAL_NO_IMPL="스프린트 %s의 구현체가 없습니다. 실행: harn implement"
    I18N_EVAL_STEP="스프린트 %s — 평가 (반복 %s)"
    I18N_EVAL_RUNNING_CHECKS="자동화 검사 실행 중..."
    I18N_EVAL_CHECKS_DONE="검사 완료 →"
    I18N_EVAL_SHUTTING_DOWN="E2E 환경 종료 중..."
    I18N_EVAL_EXEC_ERROR="스프린트 %s: 이밸류에이터 실행 오류 (종료 코드 %s) — 루프 중단"
    I18N_EVAL_MANUAL_RESUME="수동 재개: 문제를 수정한 후 harn evaluate 또는 harn implement를 실행하세요"
    I18N_EVAL_PASS="스프린트 %s: ${G}PASS${N}"
    I18N_EVAL_NEXT="다음 단계: harn next"
    I18N_EVAL_FAIL="스프린트 %s: QA ${Y}FAIL${N} (반복 %s / %s) — 자동 재시도 중... (리포트: %s)"
    # cmd_next
    I18N_NEXT_STEP="마무리"
    I18N_NEXT_DONE="백로그: ${W}%s${N} → 완료"
    I18N_NEXT_COMPLETE="${G}태스크 완전 완료: %s${N}"
    # _sprint_advance
    I18N_SPRINT_SWITCH="스프린트 %s로 전환"
    # cmd_stop
    I18N_STOP_NO_PID="실행 중인 프로세스를 찾을 수 없습니다 (PID 파일 없음)"
    I18N_STOP_ALREADY_HINT="이미 중단됐거나 harn start로 시작되지 않은 프로세스입니다."
    I18N_STOP_STALE_PID="PID=%s 프로세스가 이미 중단됨 — PID 파일 정리 중"
    I18N_STOP_STOPPING="프로세스 중단 중... (PID: ${W}%s${N})"
    I18N_STOP_SIGKILL="SIGTERM 후에도 실행 중 — SIGKILL 전송 중"
    I18N_STOP_RUN_STOPPED="실행 중단됨"
    I18N_STOP_DONE="프로세스 중단됨"
    # git helpers
    I18N_GIT_BACKLOG_COMMITTED="스프린트 백로그 커밋됨"
    I18N_GIT_BACKLOG_UNCHANGED="백로그 파일 변경 없음 — 커밋 건너뜀"
    I18N_GIT_IMPL_COMMIT="Git: 스프린트 %s 구현 커밋"
    I18N_GIT_NO_CHANGES="커밋할 변경 사항 없음 — 제너레이터가 파일을 수정하지 않았을 수 있습니다"
    I18N_GIT_COMMIT_DONE="커밋 완료: ${W}%s${N}"
    I18N_GIT_FINAL_COMMIT="Git: 최종 커밋"
    # cmd_retrospective
    I18N_RETRO_NO_CLI="AI CLI 없음 — 회고 건너뜀"
    I18N_RETRO_STEP="회고"
    I18N_RETRO_ANALYZING="AI(${W}%s${N}) 회고 분석 중..."
    I18N_RETRO_FAILED="회고 생성 실패 — 건너뜀"
    I18N_RETRO_SUMMARY_TITLE="  회고 요약"
    I18N_RETRO_PROMPT_ADD="  %s 프롬프트에 이 제안을 추가할까요? [y/N]: "
    I18N_RETRO_ADDED="%s 프롬프트에 추가됨: ${W}%s${N}"
    I18N_RETRO_SKIPPED="%s 제안 건너뜀"
    I18N_RETRO_APPLIED="프롬프트 개선 사항 적용됨."
    I18N_RETRO_COMPLETE="회고 완료 — 결과: ${W}%s${N}"
    # _run_sprint_loop
    I18N_LOOP_STARTED="루프 시작 (최대 %s 스프린트)"
    I18N_LOOP_INTERRUPTED="사용자에 의해 중단됨."
    I18N_LOOP_TERMINATED="종료 신호를 받았습니다."
    I18N_LOOP_SPRINT_PASSED="스프린트 %s 이미 완료 — 다음으로 이동"
    I18N_LOOP_SPRINT_MAX_ITER="스프린트 %s가 최대 반복 횟수(%s)에 도달 — 강제 진행"
    I18N_LOOP_EVAL_ERROR="이밸류에이터 오류 — 루프 중단. 문제를 수정한 후 harn evaluate를 실행하세요."
    I18N_LOOP_MAX_ITER_ADVANCE="스프린트 %s: 최대 반복 횟수(%s) 도달 — QA 통과 없이 강제 진행"
    I18N_LOOP_ALL_COMPLETE="${G}전체 %s 스프린트 완료!${N}"
    I18N_LOOP_SPRINT_DONE="스프린트 %s 완료 — 스프린트 %s로 전환"
    # cmd_discover
    I18N_DISCOVER_STEP="백로그 발굴 — 코드베이스 분석"
    I18N_DISCOVER_NO_ITEMS="새 항목을 추출할 수 없습니다 — 확인하세요: %s"
    I18N_DISCOVER_BACKLOG_CREATED="백로그 파일 생성됨:"
    I18N_DISCOVER_ADDED="백로그에 새 항목 추가됨"
    I18N_DISCOVER_HINT="확인: harn backlog   /   지금 시작: harn auto"
    # cmd_add
    I18N_ADD_STEP="백로그 항목 추가"
    I18N_ADD_BACKLOG_CREATED="백로그 파일 생성됨:"
    I18N_ADD_BOX_TITLE="✚ 새 백로그 항목"
    I18N_ADD_BOX_DESC="구현하려는 기능 또는 작업을 설명하세요."
    I18N_ADD_BOX_AI="AI가 슬러그와 설명을 생성해 백로그에 추가합니다."
    I18N_ADD_BOX_HINT="여러 줄 입력 가능  ·  빈 줄로 종료"
    I18N_ADD_CANCELLED="입력 없음 — 취소됨"
    I18N_ADD_NO_CLI="AI CLI를 찾을 수 없습니다. copilot 또는 claude를 설치하세요."
    I18N_ADD_GENERATING="AI(${W}%s${N}) 백로그 항목 생성 중..."
    I18N_ADD_FAILED="AI 생성 실패"
    I18N_ADD_NO_ITEMS="항목을 추출할 수 없습니다 — 확인하세요: %s"
    I18N_ADD_DONE="백로그에 추가됨:"
    I18N_ADD_HINT="확인: ${W}harn backlog${N}   /   지금 시작: ${W}harn start${N}"
    # cmd_auto
    I18N_AUTO_STEP="자동 모드"
    I18N_AUTO_RESUMING="진행 중인 실행 재개: ${W}%s${N}  (스프린트 %s · %s)"
    I18N_AUTO_CANCELLED="마지막 실행이 취소됨 — 다음 항목을 찾는 중"
    I18N_AUTO_COMPLETED="마지막 실행 완료 (${W}%s${N}) — 다음 항목을 찾는 중"
    I18N_AUTO_STARTING="다음 백로그 항목 시작: ${W}%s${N}"
    I18N_AUTO_EMPTY="백로그가 비어 있습니다."
    I18N_AUTO_FIRST_DISCOVERED="첫 번째 발굴 항목 시작: ${W}%s${N}"
    # cmd_all
    I18N_ALL_NO_BACKLOG="백로그 파일을 찾을 수 없습니다:"
    I18N_ALL_NO_PENDING="대기 중인 항목이 없습니다."
    I18N_ALL_HINT="항목 추가: ${W}harn discover${N}  또는  ${W}harn add${N}"
    I18N_ALL_STEP="전체 자동 실행 —"
    I18N_ALL_STARTING="[%s/%s] 항목 시작: ${W}%s${N}"
    I18N_ALL_COMPLETE_ITEM="[%s/%s] 완료: ${W}%s${N}"
    I18N_ALL_FAILED_ITEM="[%s/%s] 실패: ${W}%s${N} — 다음 항목으로 계속"
    I18N_ALL_FAILED_ITEMS="실패한 항목:"
    I18N_ALL_RETRY_HINT="실패 항목 수동 재실행: ${W}harn start <slug>${N}"
    I18N_ALL_RETRO_STEP="회고 실행 중 (%s개 항목)"
    I18N_ALL_RETRO_ITEM="회고: ${W}%s${N}"
    # cmd_status
    I18N_STATUS_NO_RUN="활성 실행 없음. 시작하려면: ${W}harn start${N}"
    I18N_STATUS_RUN_ID="실행 ID:"
    I18N_STATUS_ITEM="항목:"
    I18N_STATUS_SPRINT="현재 스프린트:"
    I18N_STATUS_SPRINTS="스프린트:"
    I18N_STATUS_NO_SPRINTS="(스프린트 없음)"
    # cmd_config show
    I18N_CONFIG_TITLE="harn 설정"
    I18N_CONFIG_PROJECT="  프로젝트:           "
    I18N_CONFIG_LANGUAGE="  언어:               "
    I18N_CONFIG_BACKLOG_KEY="  백로그 파일:        "
    I18N_CONFIG_MAX_RETRIES_KEY="  최대 재시도:        "
    I18N_CONFIG_GIT_KEY="  Git 통합:           "
    I18N_CONFIG_AI_MODELS="AI 모델"
    I18N_CONFIG_CUSTOM_PROMPTS_KEY="  커스텀 프롬프트:    "
    I18N_CONFIG_NO_FILE=".harn_config 파일이 없습니다. ${W}harn init${N}을 먼저 실행하세요."
    I18N_CONFIG_SET_FILE_NOT_FOUND=".harn_config 파일이 없습니다. ${W}harn init${N}을 먼저 실행하세요."
    I18N_CONFIG_NO_CLI="AI CLI를 찾을 수 없습니다. copilot 또는 claude를 설치하세요."
    I18N_CONFIG_NO_HINTS="설정에 HINT_* / GIT_GUIDE 값이 없습니다. 재생성할 내용이 없습니다."
    I18N_CONFIG_HINT_HOW="힌트 추가 방법: ${W}harn config set HINT_PLANNER \"내용\"${N}"
    I18N_CONFIG_REGEN_STEP="커스텀 프롬프트 재생성 중"
    I18N_CONFIG_REGEN_INFO="AI CLI(${W}%s${N})로 프롬프트 재생성 중..."
    I18N_CONFIG_REGEN_DONE="커스텀 프롬프트 재생성됨: ${W}%s${N}"
    I18N_CONFIG_UNKNOWN_SUB="알 수 없는 서브명령어:"
    I18N_CONFIG_USAGE="사용법: harn config [show|set KEY VALUE|regen]"
    # cmd_runs
    I18N_RUNS_TITLE="harn 실행 목록:"
    # cmd_resume
    I18N_RESUME_USAGE="사용법: harn resume <run-id>"
    I18N_RESUME_NOT_FOUND="실행을 찾을 수 없습니다:"
    I18N_RESUME_OK="재개됨:"
    # cmd_tail
    I18N_TAIL_FALLBACK="current.log 없음 — 최근 실행 로그로 대체:"
    I18N_TAIL_NO_LOG="활성 로그 없음. 먼저 실행하세요: harn auto"
    I18N_TAIL_TAILING="로그 실시간 출력:"
    # _ask_user_instructions
    I18N_INSTRUCTIONS_TITLE="💬 추가 지시사항"
    I18N_INSTRUCTIONS_ENTER="%s에게 전달할 지시사항을 입력하세요."
    I18N_INSTRUCTIONS_HINT="빈 줄 = 건너뜀  ·  여러 줄 입력 가능"
    I18N_INSTRUCTIONS_PASSED="✓  다음 에이전트에게 전달됩니다."
    # memory
    I18N_MEMORY_SAVED="프로젝트 메모리에 학습 내용 저장됨"
    # routing
    I18N_ROUTING_UPGRADED="모델 업그레이드됨"
    I18N_ROUTING_DOWNGRADED="모델 다운그레이드됨"
    # update
    I18N_UPDATE_AVAILABLE="업데이트 가능"
    # nlp
    I18N_NLP_USAGE="사용법: harn do \"<자연어 요청>\""
    I18N_NLP_ANALYZING="요청 분석 중..."
    I18N_NLP_FAILED="요청 분석에 실패했습니다"
    I18N_NLP_NO_MATCH="적절한 명령을 결정할 수 없습니다"
    I18N_NLP_ROUTED="→ %s"
    I18N_NLP_GENERATING="백로그 항목 생성 중..."
    I18N_NLP_ITEMS_PREVIEW="추가할 항목:"
    I18N_NLP_NO_ITEMS="항목이 생성되지 않았습니다"
    I18N_NLP_CONFIRM_ADD="백로그에 추가할까요?"
    I18N_NLP_YES="네, 추가"
    I18N_NLP_NO="취소"
    I18N_NLP_CANCELLED="취소됨"
    I18N_NLP_SELECT_VALUE="새 값을 선택하세요:"
    I18N_NLP_CONFIG_APPLIED="적용됨: %s → %s"
    # team
    I18N_TEAM_NO_TMUX="team 모드에는 tmux가 필요합니다. 설치: brew install tmux"
    I18N_TEAM_USAGE="사용법: harn team [에이전트수] <작업 설명>"
    I18N_TEAM_LAUNCHING="%d개 병렬 에이전트 시작"
    I18N_TEAM_STARTED="팀 세션 시작됨: %s"
    # eval continuation enforcement
    I18N_EVAL_NO_CHANGES="PASS 판정이지만 실제 파일 변경 없음 — FAIL로 재정의 (Sprint %s)"
  else
    I18N_LANG_NAME="English"
    I18N_INIT_LANG_PROMPT="Language"
    I18N_INIT_BACKLOG_PROMPT="Backlog file path (relative to project root)"
    I18N_INIT_BACKLOG_DEFAULT="sprint-backlog.md"
    I18N_INIT_MAX_QA_PROMPT="Max QA retry count"
    I18N_INIT_GIT_PROMPT="Enable Git integration"
    I18N_INIT_SAVED="Configuration saved"
    I18N_DOCTOR_TITLE="harn environment check"
    I18N_DOCTOR_OK="OK"
    I18N_DOCTOR_WARN="WARN"
    I18N_DOCTOR_FAIL="FAIL"
    I18N_CONFIG_SET_DONE="Config saved"
    I18N_CONFIG_SET_USAGE="Usage: harn config set <key> <value>"
    I18N_LANG_SELECT="Select language"
    # usage()
    I18N_USAGE_TITLE="Usage"
    I18N_USAGE_CMD="harn <command>"
    I18N_USAGE_SETUP="Setup"
    I18N_USAGE_BACKLOG="Backlog"
    I18N_USAGE_RUN="Run"
    I18N_USAGE_STEPS="Step by step"
    I18N_USAGE_MONITOR="Monitoring"
    I18N_USAGE_INIT="Initial setup (first run or reconfigure)"
    I18N_USAGE_CONFIG="Show current configuration"
    I18N_USAGE_CONFIG_SET="Update a specific setting"
    I18N_USAGE_CONFIG_REGEN="Regenerate custom prompts from HINT_* values"
    I18N_USAGE_BACKLOG_CMD="List pending items"
    I18N_USAGE_ADD="Add new backlog item (AI-assisted)"
    I18N_USAGE_DISCOVER="Analyze codebase and discover new items"
    I18N_USAGE_START="Select an item and run the full loop"
    I18N_USAGE_AUTO="Auto-detect: resume / start / discover"
    I18N_USAGE_ALL="Run all pending items sequentially (retro at end)"
    I18N_USAGE_PLAN="Re-run planner"
    I18N_USAGE_CONTRACT="Scope negotiation"
    I18N_USAGE_IMPLEMENT="Run generator"
    I18N_USAGE_EVALUATE="Run evaluator"
    I18N_USAGE_NEXT="Advance to next sprint"
    I18N_USAGE_STATUS="Current run status"
    I18N_USAGE_TAIL="Live log output"
    I18N_USAGE_RUNS="List all runs"
    I18N_USAGE_RESUME="Resume a previous run"
    I18N_USAGE_STOP="Stop the loop"
    I18N_USAGE_TIP="You can inject extra instructions between steps during a loop run."
    I18N_USAGE_SMART="Smart"
    I18N_USAGE_DO="Natural language command (AI routes to action)"
    I18N_USAGE_TEAM="Parallel agents via tmux (N = agent count)"
    I18N_WELCOME_TIPS="Getting started"
    I18N_WELCOME_DOCTOR="Check environment"
    # doctor
    I18N_DOCTOR_VERSION="Version"
    I18N_DOCTOR_BACKENDS="AI Backends"
    I18N_DOCTOR_NOT_FOUND="not found"
    I18N_DOCTOR_INSTALL="Install"
    I18N_DOCTOR_ACTIVE_BACKEND="Active backend"
    I18N_DOCTOR_NO_BACKEND="No AI backend available — run: harn init"
    I18N_DOCTOR_GIT_SECTION="Git"
    I18N_DOCTOR_GH_AUTH_WARN="not authenticated — run: gh auth login"
    I18N_DOCTOR_GH_NOT_FOUND="not found"
    I18N_DOCTOR_PROJECT_REPO="Project repo"
    I18N_DOCTOR_CONFIG_SECTION="harn Config"
    I18N_DOCTOR_CONFIG_FOUND="found"
    I18N_DOCTOR_CONFIG_NOT_FOUND="not configured  (run harn init to set up)"
    I18N_DOCTOR_GIT_INTEGRATION="Git integration"
    I18N_DOCTOR_SPRINT_COUNT="Sprint count"
    I18N_DOCTOR_AI_BACKEND="AI backend"
    I18N_DOCTOR_CUSTOM_PROMPTS="Custom prompts"
    I18N_DOCTOR_MODELS="Models"
    I18N_DOCTOR_ACTIVE_RUN="Active Run"
    I18N_DOCTOR_SPRINT="Sprint"
    I18N_DOCTOR_NO_RUN="No active run"
    I18N_DOCTOR_DEPS="Other Dependencies"
    I18N_DOCTOR_OPTIONAL="optional"
    I18N_DOCTOR_ALL_OK="All critical checks passed."
    I18N_DOCTOR_FAIL_MSG="One or more critical checks failed. Run: harn init"
    # no-config warning
    I18N_NO_CONFIG_WARN="No .harn_config found in this directory."
    I18N_NO_CONFIG_SETUP="Starting initial setup..."
    # cmd_init
    I18N_INIT_TITLE="harn initial setup"
    I18N_INIT_OVERWRITE="Config file already exists. Overwrite? [y/N]: "
    I18N_INIT_CANCELLED="Initialization cancelled"
    I18N_INIT_AI_MODELS="AI model settings"
    I18N_INIT_AI_MODELS_HINT="Use ↑↓ arrows to navigate, Enter to select, Ctrl+Q to cancel init"
    I18N_INIT_SPRINT_STRUCTURE="Sprint structure"
    I18N_INIT_SPRINT_COUNT_PROMPT="Number of sprints [2]: "
    I18N_INIT_SPRINT_ROLES_HINT="Describe the goal/role of each sprint (Enter = use default label)"
    I18N_INIT_SPRINT_ROLE_PROMPT="  Sprint %s role: "
    I18N_INIT_SPRINT_INVALID="Invalid sprint count '%s' — defaulting to 2"
    I18N_INIT_GIT_SECTION="Git integration"
    I18N_INIT_GIT_ENABLE_PROMPT="Enable Git integration? [y/N]: "
    I18N_INIT_GIT_GUIDE_TITLE="Git commit guidelines"
    I18N_INIT_GIT_GUIDE_HINT="Enter commit conventions, etc.\n  These guidelines will be reflected in all agent prompts. (Enter = skip)"
    I18N_INIT_HINTS_TITLE="Per-agent special instructions"
    I18N_INIT_HINTS_HINT="Enter project architecture, tech stack, coding conventions, etc.\n  The AI CLI will naturally integrate these into the base prompts. (Enter = skip)"
    I18N_INIT_HINT_PLANNER="Planner   — spec/sprint planning instructions: "
    I18N_INIT_HINT_GENERATOR="Generator — implementation instructions: "
    I18N_INIT_HINT_EVALUATOR="Evaluator — QA/evaluation instructions: "
    I18N_INIT_CONFIG_SAVED="Config file created"
    I18N_INIT_GEN_PROMPTS="Generating custom prompts with AI CLI"
    I18N_INIT_COMPLETE="Initialization complete!"
    I18N_INIT_HINT_BACKLOG="  harn backlog  — view backlog items"
    I18N_INIT_HINT_START="  harn start    — start the loop"
    # AI CLI check / backend selection
    I18N_NO_AI_CLI="${R}✗ No AI CLI found.${N}"
    I18N_NO_AI_CLI_HINT="harn requires GitHub Copilot CLI, Claude CLI, OpenAI Codex CLI, or Gemini CLI."
    I18N_AI_BACKEND_TITLE="Default AI backend"
    I18N_AI_USING_COPILOT="${G}✓${N} Using ${W}copilot${N} (GitHub Copilot CLI detected)"
    I18N_AI_USING_CLAUDE="${G}✓${N} Using ${W}claude${N} (Anthropic Claude CLI detected)"
    I18N_AI_USING_CODEX="${G}✓${N} Using ${W}codex${N} (OpenAI Codex CLI detected)"
    I18N_AI_USING_GEMINI="${G}✓${N} Using ${W}gemini${N} (Google Gemini CLI detected)"
    # cmd_backlog
    I18N_BACKLOG_TITLE="Pending backlog items:"
    I18N_BACKLOG_EMPTY="(none — all done!)"
    I18N_BACKLOG_RUN="Run: ${W}harn start${N} — select a backlog item and run the full loop"
    # cmd_start
    I18N_START_SELECT_ITEM="Select backlog item"
    I18N_START_NO_PENDING="No pending items in backlog. Add an item first."
    I18N_START_DISCOVER_HINT="To discover items: harn discover"
    I18N_START_ENTER_NUM="Enter number (1–%s): "
    I18N_START_SPRINT_COUNT_PROMPT="Number of sprints [1]: "
    I18N_START_SPRINT_COUNT_INVALID="Invalid sprint count — defaulting to 1"
    I18N_START_SELECTED="Selected:"
    I18N_START_INVALID="Invalid input:"
    I18N_START_RUN_CREATED="Run created:"
    I18N_START_VIEW_LOG="View live log: ${W}harn tail${N}  →"
    I18N_START_PLAN_FAILED="Failed at initial planning stage. Check the log and retry:"
    I18N_START_AUTO_LOOP="Starting automated run"
    I18N_START_LOOP_DETAIL="Initialization complete. Running sprint loop automatically (contract → implement → evaluate → next, up to %s sprints)."
    I18N_START_LOOP_INTERRUPTED="Automated sprint loop was interrupted. Check the failure point and resume with 'harn resume %s'."
    I18N_START_COMPLETE="harn start full automated run complete"
    I18N_START_MAX_SPRINT="Reached max sprint count (%s). Automated run ended. Run 'harn start' to continue."
    # cmd_plan
    I18N_PLAN_STEP="Planning phase"
    I18N_PLAN_TEXT_NOT_FOUND="plan.text not found — using slug/prompt as plan text"
    I18N_PLAN_MARKERS_NOT_FOUND="Section markers not found — saving full output as spec.md"
    I18N_PLAN_ITEM_IN_PROGRESS="Backlog: ${W}%s${N} → In Progress"
    I18N_PLAN_LINE_UPDATED="Backlog plan line updated:"
    I18N_PLAN_LINE_FAILED="Backlog plan update failed: slug not found"
    I18N_PLAN_LINE_UNCHANGED="Backlog plan line unchanged (already up to date)"
    I18N_PLAN_LINE_EXCEPTION="Exception during backlog plan update"
    I18N_PLAN_COMPLETE="Planning complete"
    # cmd_contract
    I18N_CONTRACT_EXISTS="Scope already exists. Delete %s to recreate it."
    I18N_CONTRACT_STEP="Sprint %s — scope negotiation"
    I18N_CONTRACT_REVIEWING="Evaluator reviewing scope..."
    I18N_CONTRACT_APPROVED="Sprint %s scope approved"
    I18N_CONTRACT_NEEDS_REVISION="Scope needs revision — revising..."
    I18N_CONTRACT_REVISED="Sprint %s scope revision complete"
    I18N_CONTRACT_NEXT="Next step: harn implement"
    # cmd_implement
    I18N_IMPL_NO_SCOPE="No scope for sprint %s. Run: harn contract"
    I18N_IMPL_STEP="Sprint %s — development (iteration %s)"
    I18N_IMPL_COMPLETE="Sprint %s implementation complete (iteration %s)"
    I18N_IMPL_NEXT="Next step: harn evaluate"
    # cmd_evaluate
    I18N_EVAL_NO_IMPL="No implementation for sprint %s. Run: harn implement"
    I18N_EVAL_STEP="Sprint %s — evaluation (iteration %s)"
    I18N_EVAL_RUNNING_CHECKS="Running automated checks..."
    I18N_EVAL_CHECKS_DONE="Checks complete →"
    I18N_EVAL_SHUTTING_DOWN="Shutting down E2E environment..."
    I18N_EVAL_EXEC_ERROR="Sprint %s: evaluator execution error (exit %s) — stopping loop"
    I18N_EVAL_MANUAL_RESUME="Manual resume: fix the issue then run harn evaluate  or  harn implement"
    I18N_EVAL_PASS="Sprint %s: ${G}PASS${N}"
    I18N_EVAL_NEXT="Next step: harn next"
    I18N_EVAL_FAIL="Sprint %s: QA ${Y}FAIL${N} (iteration %s / %s) — retrying automatically... (report: %s)"
    # cmd_next
    I18N_NEXT_STEP="Finishing up"
    I18N_NEXT_DONE="Backlog: ${W}%s${N} → Done"
    I18N_NEXT_COMPLETE="${G}Task fully complete: %s${N}"
    # _sprint_advance
    I18N_SPRINT_SWITCH="Switching to sprint %s"
    # cmd_stop
    I18N_STOP_NO_PID="No running harness found (PID file missing)"
    I18N_STOP_ALREADY_HINT="Already stopped or was not started with harn start."
    I18N_STOP_STALE_PID="Process PID=%s already stopped — cleaning up PID file"
    I18N_STOP_STOPPING="Stopping harness... (PID: ${W}%s${N})"
    I18N_STOP_SIGKILL="Still running after SIGTERM — sending SIGKILL"
    I18N_STOP_RUN_STOPPED="Run stopped"
    I18N_STOP_DONE="Harness stopped"
    # git helpers
    I18N_GIT_BACKLOG_COMMITTED="Sprint backlog committed"
    I18N_GIT_BACKLOG_UNCHANGED="Backlog file unchanged — skipping commit"
    I18N_GIT_IMPL_COMMIT="Git: Sprint %s implementation commit"
    I18N_GIT_NO_CHANGES="No changes to commit — generator may not have modified any files"
    I18N_GIT_COMMIT_DONE="Commit done: ${W}%s${N}"
    I18N_GIT_FINAL_COMMIT="Git: final commit"
    # cmd_retrospective
    I18N_RETRO_NO_CLI="No AI CLI — skipping retrospective"
    I18N_RETRO_STEP="Retrospective"
    I18N_RETRO_ANALYZING="AI(${W}%s${N}) analyzing retrospective..."
    I18N_RETRO_FAILED="Retrospective generation failed — skipping"
    I18N_RETRO_SUMMARY_TITLE="  Retrospective Summary"
    I18N_RETRO_PROMPT_ADD="  Add this suggestion to the ${W}%s${N} prompt? [y/N]: "
    I18N_RETRO_ADDED="Added to %s prompt: ${W}%s${N}"
    I18N_RETRO_SKIPPED="%s suggestion skipped"
    I18N_RETRO_APPLIED="Prompt improvements applied."
    I18N_RETRO_COMPLETE="Retrospective complete — results: ${W}%s${N}"
    # _run_sprint_loop
    I18N_LOOP_STARTED="Loop started (up to %s sprints)"
    I18N_LOOP_INTERRUPTED="Harness interrupted by user."
    I18N_LOOP_TERMINATED="Harness received termination signal."
    I18N_LOOP_SPRINT_PASSED="Sprint %s already passed — moving to next"
    I18N_LOOP_SPRINT_MAX_ITER="Sprint %s already reached max iterations (%s) — forcing advance"
    I18N_LOOP_EVAL_ERROR="Evaluator process error — stopping loop. Fix the issue and run harn evaluate."
    I18N_LOOP_MAX_ITER_ADVANCE="Sprint %s: max iterations (%s) reached — forcing advance without QA pass"
    I18N_LOOP_ALL_COMPLETE="${G}All %s sprints complete!${N}"
    I18N_LOOP_SPRINT_DONE="Sprint %s done — switching to sprint %s"
    # cmd_discover
    I18N_DISCOVER_STEP="Backlog discovery — codebase analysis"
    I18N_DISCOVER_NO_ITEMS="Could not extract new items — check %s."
    I18N_DISCOVER_BACKLOG_CREATED="Backlog file created:"
    I18N_DISCOVER_ADDED="New items added to backlog"
    I18N_DISCOVER_HINT="Check: harn backlog   /   Start now: harn auto"
    # cmd_add
    I18N_ADD_STEP="Adding backlog item"
    I18N_ADD_BACKLOG_CREATED="Backlog file created:"
    I18N_ADD_BOX_TITLE="✚ New backlog item"
    I18N_ADD_BOX_DESC="Describe the feature or task you want to implement."
    I18N_ADD_BOX_AI="AI will generate a slug and description and add it to the backlog."
    I18N_ADD_BOX_HINT="Multi-line input supported  ·  Empty line to finish"
    I18N_ADD_CANCELLED="No input — cancelled"
    I18N_ADD_NO_CLI="AI CLI not found. Install copilot or claude."
    I18N_ADD_GENERATING="AI(${W}%s${N}) generating backlog items..."
    I18N_ADD_FAILED="AI generation failed"
    I18N_ADD_NO_ITEMS="Could not extract items — check %s."
    I18N_ADD_DONE="Added to backlog:"
    I18N_ADD_HINT="Check: ${W}harn backlog${N}   /   Start now: ${W}harn start${N}"
    # cmd_auto
    I18N_AUTO_STEP="Auto mode"
    I18N_AUTO_RESUMING="Resuming in-progress run: ${W}%s${N}  (sprint %s · %s)"
    I18N_AUTO_CANCELLED="Last run was cancelled — looking for next item"
    I18N_AUTO_COMPLETED="Last run completed (${W}%s${N}) — looking for next item"
    I18N_AUTO_STARTING="Starting next backlog item: ${W}%s${N}"
    I18N_AUTO_EMPTY="Backlog is empty."
    I18N_AUTO_FIRST_DISCOVERED="Starting first discovered item: ${W}%s${N}"
    # cmd_all
    I18N_ALL_NO_BACKLOG="Backlog file not found:"
    I18N_ALL_NO_PENDING="No pending items in backlog."
    I18N_ALL_HINT="To add items: ${W}harn discover${N}  or  ${W}harn add${N}"
    I18N_ALL_STEP="Full automated run —"
    I18N_ALL_STARTING="[%s/%s] Starting item: ${W}%s${N}"
    I18N_ALL_COMPLETE_ITEM="[%s/%s] Complete: ${W}%s${N}"
    I18N_ALL_FAILED_ITEM="[%s/%s] Failed: ${W}%s${N} — continuing with next item"
    I18N_ALL_FAILED_ITEMS="Failed items:"
    I18N_ALL_RETRY_HINT="Re-run failed items manually: ${W}harn start <slug>${N}"
    I18N_ALL_RETRO_STEP="Running retrospective (%s item(s))"
    I18N_ALL_RETRO_ITEM="Retrospective: ${W}%s${N}"
    # cmd_status
    I18N_STATUS_NO_RUN="No active run. Start with: ${W}harn start${N}"
    I18N_STATUS_RUN_ID="Run ID:"
    I18N_STATUS_ITEM="Item:"
    I18N_STATUS_SPRINT="Current sprint:"
    I18N_STATUS_SPRINTS="Sprints:"
    I18N_STATUS_NO_SPRINTS="(no sprints)"
    # cmd_config show
    I18N_CONFIG_TITLE="harn Configuration"
    I18N_CONFIG_PROJECT="  Project:           "
    I18N_CONFIG_LANGUAGE="  Language:          "
    I18N_CONFIG_BACKLOG_KEY="  Backlog file:      "
    I18N_CONFIG_MAX_RETRIES_KEY="  Max retries:       "
    I18N_CONFIG_GIT_KEY="  Git integration:   "
    I18N_CONFIG_AI_MODELS="AI Models"
    I18N_CONFIG_CUSTOM_PROMPTS_KEY="  Custom prompts:    "
    I18N_CONFIG_NO_FILE="No .harn_config file. Run ${W}harn init${N} first."
    I18N_CONFIG_SET_FILE_NOT_FOUND=".harn_config file not found. Run ${W}harn init${N} first."
    I18N_CONFIG_NO_CLI="No AI CLI found. Install copilot or claude."
    I18N_CONFIG_NO_HINTS="No HINT_* / GIT_GUIDE values in config. Nothing to regenerate."
    I18N_CONFIG_HINT_HOW="To add hints: ${W}harn config set HINT_PLANNER \"hint content\"${N}"
    I18N_CONFIG_REGEN_STEP="Regenerating custom prompts"
    I18N_CONFIG_REGEN_INFO="Regenerating prompts with AI CLI (${W}%s${N})..."
    I18N_CONFIG_REGEN_DONE="Custom prompts regenerated: ${W}%s${N}"
    I18N_CONFIG_UNKNOWN_SUB="Unknown config subcommand:"
    I18N_CONFIG_USAGE="Usage: harn config [show|set KEY VALUE|regen]"
    # cmd_runs
    I18N_RUNS_TITLE="Harness runs:"
    # cmd_resume
    I18N_RESUME_USAGE="Usage: harn resume <run-id>"
    I18N_RESUME_NOT_FOUND="Run not found:"
    I18N_RESUME_OK="Resumed:"
    # cmd_tail
    I18N_TAIL_FALLBACK="No current.log — falling back to latest run log:"
    I18N_TAIL_NO_LOG="No active log. Start a run first: harn auto"
    I18N_TAIL_TAILING="Tailing log:"
    # _ask_user_instructions
    I18N_INSTRUCTIONS_TITLE="💬 Additional instructions"
    I18N_INSTRUCTIONS_ENTER="Enter instructions to pass to %s."
    I18N_INSTRUCTIONS_HINT="Empty line = skip  ·  Multi-line input supported"
    I18N_INSTRUCTIONS_PASSED="✓  Will be passed to the next agent."
    # memory
    I18N_MEMORY_SAVED="Learning saved to project memory"
    # routing
    I18N_ROUTING_UPGRADED="Model upgraded"
    I18N_ROUTING_DOWNGRADED="Model downgraded"
    # update
    I18N_UPDATE_AVAILABLE="Update available"
    # nlp
    I18N_NLP_USAGE="Usage: harn do \"<natural language request>\""
    I18N_NLP_ANALYZING="Analyzing request..."
    I18N_NLP_FAILED="Failed to analyze request"
    I18N_NLP_NO_MATCH="Could not determine the right action"
    I18N_NLP_ROUTED="→ %s"
    I18N_NLP_GENERATING="Generating backlog items..."
    I18N_NLP_ITEMS_PREVIEW="Items to add:"
    I18N_NLP_NO_ITEMS="No items generated"
    I18N_NLP_CONFIRM_ADD="Add to backlog?"
    I18N_NLP_YES="Yes, add"
    I18N_NLP_NO="Cancel"
    I18N_NLP_CANCELLED="Cancelled"
    I18N_NLP_SELECT_VALUE="Select new value:"
    I18N_NLP_CONFIG_APPLIED="Applied: %s → %s"
    # team
    I18N_TEAM_NO_TMUX="tmux is required for team mode. Install: brew install tmux"
    I18N_TEAM_USAGE="Usage: harn team [count] <task description>"
    I18N_TEAM_LAUNCHING="Launching %d parallel agents"
    I18N_TEAM_STARTED="Team session started: %s"
    # eval continuation enforcement
    I18N_EVAL_NO_CHANGES="PASS verdict but no actual file changes — overriding to FAIL (Sprint %s)"
  fi
}

load_config() {
  [[ ! -f "$CONFIG_FILE" ]] && return

  # shellcheck source=/dev/null
  source "$CONFIG_FILE"

  # Convert relative BACKLOG_FILE path → absolute path
  if [[ -n "${BACKLOG_FILE:-}" && "${BACKLOG_FILE}" != /* ]]; then
    BACKLOG_FILE="$ROOT_DIR/$BACKLOG_FILE"
  fi
  BACKLOG_FILE_DISPLAY="$BACKLOG_FILE"

  # Apply MODEL_* vars from config → internal COPILOT_MODEL_* (env override takes precedence)
  COPILOT_MODEL_PLANNER="${HARN_MODEL_PLANNER:-${MODEL_PLANNER:-$COPILOT_MODEL_PLANNER}}"
  COPILOT_MODEL_GENERATOR_CONTRACT="${HARN_MODEL_GENERATOR_CONTRACT:-${MODEL_GENERATOR_CONTRACT:-$COPILOT_MODEL_GENERATOR_CONTRACT}}"
  COPILOT_MODEL_GENERATOR_IMPL="${HARN_MODEL_GENERATOR_IMPL:-${MODEL_GENERATOR_IMPL:-$COPILOT_MODEL_GENERATOR_IMPL}}"
  COPILOT_MODEL_EVALUATOR_CONTRACT="${HARN_MODEL_EVALUATOR_CONTRACT:-${MODEL_EVALUATOR_CONTRACT:-$COPILOT_MODEL_EVALUATOR_CONTRACT}}"
  COPILOT_MODEL_EVALUATOR_QA="${HARN_MODEL_EVALUATOR_QA:-${MODEL_EVALUATOR_QA:-$COPILOT_MODEL_EVALUATOR_QA}}"

  # Apply AI_BACKEND from config (env override takes precedence)
  AI_BACKEND="${HARN_AI_BACKEND:-${AI_BACKEND:-}}"

  # Per-role backend overrides (fall back to global AI_BACKEND)
  AI_BACKEND_PLANNER="${AI_BACKEND_PLANNER:-$AI_BACKEND}"
  AI_BACKEND_GENERATOR_CONTRACT="${AI_BACKEND_GENERATOR_CONTRACT:-$AI_BACKEND}"
  AI_BACKEND_GENERATOR_IMPL="${AI_BACKEND_GENERATOR_IMPL:-$AI_BACKEND}"
  AI_BACKEND_EVALUATOR_CONTRACT="${AI_BACKEND_EVALUATOR_CONTRACT:-$AI_BACKEND}"
  AI_BACKEND_EVALUATOR_QA="${AI_BACKEND_EVALUATOR_QA:-$AI_BACKEND}"

  # Apply sprint settings from config
  SPRINT_COUNT="${SPRINT_COUNT:-1}"
  SPRINT_ROLES="${SPRINT_ROLES:-}"

  # Re-detect language after config is sourced (LANG_OVERRIDE now available)
  _detect_lang
  _i18n_load
  # Set lang-aware PROMPTS_DIR (builtin: $SCRIPT_DIR/prompts/$HARN_LANG, fallback to en)
  local lang_dir="$SCRIPT_DIR/prompts/$HARN_LANG"
  if [[ -d "$lang_dir" ]]; then
    PROMPTS_DIR="$lang_dir"
  else
    PROMPTS_DIR="$SCRIPT_DIR/prompts/en"
  fi

  # Apply custom prompts directory (overrides lang-aware dir)
  if [[ -n "${CUSTOM_PROMPTS_DIR:-}" ]]; then
    local custom_abs="$CUSTOM_PROMPTS_DIR"
    [[ "${CUSTOM_PROMPTS_DIR}" != /* ]] && custom_abs="$ROOT_DIR/$CUSTOM_PROMPTS_DIR"
    if [[ -d "$custom_abs/$HARN_LANG" ]]; then
      PROMPTS_DIR="$custom_abs/$HARN_LANG"
    elif [[ -d "$custom_abs" ]]; then
      PROMPTS_DIR="$custom_abs"
    fi
  fi
}

