# lib/error.sh — Error handling and exit traps
# Sourced by harn.sh — do not execute directly

HARN_CMD_ARGS=("$@")
_HARN_ERR_LINE=""
_HARN_ERR_CMD=""
_HARN_SILENT_EXIT=0

# Record location of last bash error
trap '_HARN_ERR_LINE=$LINENO; _HARN_ERR_CMD=$BASH_COMMAND' ERR

_suggest_bug_report() {
  local error_msg="${1:-Unexpected error}"
  [[ $_HARN_SILENT_EXIT -eq 1 ]] && return 0

  echo ""
  echo -e "${Y}⚠  harn encountered an unexpected error.${N}"
  echo -e "   ${D}${error_msg}${N}"
  echo ""
  printf "   File a bug report on GitHub? [y/N]: "

  local ans=""
  if command -v python3 &>/dev/null; then
    ans=$(python3 -c '
import sys, tty, termios
fd = open("/dev/tty","rb+",buffering=0)
old = termios.tcgetattr(fd)
tty.setraw(fd)
try:
    b = fd.read(1)
    c = b.decode("utf-8","replace") if b else ""
    fd.write((c + "\r\n").encode()); fd.flush()
    print(c, end="")
except Exception: pass
finally:
    termios.tcsetattr(fd, termios.TCSADRAIN, old)
    fd.close()
' 2>/dev/null)
  else
    read -r ans
  fi
  echo ""
  [[ "$ans" != "y" && "$ans" != "Y" ]] && return 0

  # Gather context
  local os_info; os_info=$(uname -s -r 2>/dev/null || echo "unknown")
  local log_tail=""
  [[ -f "${LOG_FILE:-}" ]] && log_tail=$(tail -30 "$LOG_FILE" 2>/dev/null || echo "")
  local cmd_args="${HARN_CMD_ARGS[*]:-unknown}"
  local err_loc=""
  [[ -n "$_HARN_ERR_LINE" ]] && err_loc=" (line $_HARN_ERR_LINE: \`$_HARN_ERR_CMD\`)"

  local issue_title="Bug: ${error_msg:0:80}"
  local issue_body
  issue_body=$(cat <<ISSUE_EOF
## Bug Report

**harn version:** \`$HARN_VERSION\`
**OS:** \`$os_info\`
**Command:** \`harn $cmd_args\`
**Error:** $error_msg$err_loc

## Recent Log

\`\`\`
$log_tail
\`\`\`

---
*Auto-generated by \`harn\` error reporter*
ISSUE_EOF
)

  if command -v gh &>/dev/null && gh auth status &>/dev/null 2>&1; then
    echo -e "  ${D}Creating GitHub issue...${N}"
    local issue_url
    issue_url=$(gh issue create \
      --repo "Tyrannoapartment/harn" \
      --title "$issue_title" \
      --body "$issue_body" \
      --label "bug" 2>/dev/null)
    if [[ -n "$issue_url" ]]; then
      log_ok "Issue filed: ${W}${issue_url}${N}"
    else
      echo -e "  ${Y}Could not create issue. File manually:${N}"
      echo -e "  ${W}https://github.com/Tyrannoapartment/harn/issues/new${N}"
    fi
  else
    echo -e "  ${Y}gh CLI not authenticated. File manually:${N}"
    echo -e "  ${W}https://github.com/Tyrannoapartment/harn/issues/new${N}"
    echo ""
    echo -e "  Title: ${W}${issue_title}${N}"
  fi
  echo ""
}

_harn_on_exit() {
  local ec=$?
  # Only trigger for truly unexpected exits (not normal user-facing exits)
  # exit 0 = success, exit 1 = handled error, exit 130 = Ctrl+C
  if [[ $ec -gt 1 && $ec -ne 130 && $_HARN_SILENT_EXIT -eq 0 ]]; then
    _suggest_bug_report "Unexpected exit (code $ec)${_HARN_ERR_LINE:+ at line $_HARN_ERR_LINE}"
  fi
}
trap '_harn_on_exit' EXIT
